### PR TITLE
Adapting to only give back SPDIformat for HGVS genomic variant 

### PR DESCRIPTION
**Pull request by SonjaR-UniMan**
Module gives back SPDI variant format. Ready for integration in Main.py

### CODE REVIEW

**Comment by LMP2005** [comment]
Code looks really good. Do we need to reference Variant recoder, as that was in the original blueprint?

**Comment by ayurahman** [comment]
I was wondering about that as well. Thats why I come up w alternative version of module5 just in case we need to retrieve the spdi using variant recorder api

**Comment by SonjaR-UniMan** [comment]
I think we can follow our discussed idea to add both, it can offer extra value, as they return different data which can enrich the information. But it is good to already add the blueprint SPDI module to main branch. Eventually we can gather the SPDI functions in the calls from main.py. It looks feasible.

**Comment by SonjaR-UniMan** [comment]
Both Modules output integrated into Main.py workflow so they can be displayed as output together. Issue can be losed.

**Pull request merged**
