### PR TITLE
Team 2

### PR DESCRIPTION
**Pull request by LMP2005**
Creation of test folder. To contain Functional test for main.py and unit test for each individual module

### CODE REVIEW

**Comment by LMP2005** [comment]
Not sure what the conflicts are. I can't seem to find them on the command line.
"Resolve conflicts" in the box above on the right isn't highlighted, which indicates that it isn't straightforward. I will look into again tomorrow.

**Comment by LMP2005** [comment]
Ok I think the merge conflicts are a result of Christoph and myself both making changes to the same line of code in module2_variiabtvalidator.py in the same merge. 
We will have to break them down into different merges or only complete the final commits.

**Comment by LMP2005** [comment]
Test modules should have no conflicts, as new folder.

**Review by tophie97 — APPROVED** [review]
Looks good to me. I look forward to adding the module changes to our Main!

**Pull request closed without merging**
