### PR TITLE
Resolves issue 41

### PR DESCRIPTION
**Pull request by Lindaalnsour**
Resolves issue #41 

1) Remove the namespace from Module 1.
2) Make Module 1 usable in main.py.
- Delete the projects scripts file since replaced with Modules directory
- Set the main.py in the root directory where it should be
- Keep the logging after making sure it worked
- Did an example of how should we do points 1&2 for the rest modules and there's TODO statement for each module.

### CODE REVIEW

**Review by tophie97 — COMMENTED** [review]
Have you been able to test if it's functional on your end as yet?

**Comment by ayurahman** [comment]
Hi Linda. I have a quick look on the restructured module1. I just want to ask when you run the code did the result got printed in the terminal? The reason I asked is I didn't see any print instruction so I'm just wondering. But if it did then nothing to worry about. For module3 and 4 i dint use flask. I just use import request and import json. and of course import logger and import logger handler for the .py version with the logger one

**Comment by ayurahman** [comment]
I have run it and it seems like nothing got printed on terminal. Im not sure either so dont take my word for it.

**Comment by ayurahman** [comment]
So I suggest add print function to the code. And perhaps #Example of Usage and also logger. And need to add exception and error handling to the code as well. There will be marks for each of this I think.

**Comment by LMP2005** [comment]
I have restructured Module 2, will send for review to all. I have added the following print function to the code.
if genomic_hgvs and genomic_coordinates:
    print(f"Genomic HGVS: {genomic_hgvs}")
    print(f"Genomic Coordinates: {genomic_coordinates}")

**Comment by LMP2005** [comment]
With regards to logging, we need to create a central logger, I presume in main.py, then import into each module script. Info on how to do this is in the realpython.tutorial noted in slack.

**Pull request merged**
